import { Geist, Geist_Mono, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";

// import { StoreProvider } from "./providers/StoreContext"; // Store Provider
import { Toaster } from "react-hot-toast"; // Toast Notifications
import AuthenticateHandler from "./utils/AuthenticateHandler";
import SideNav from "./common/SideNav";
import SideNavWrapper from "./common/SideNavWrapper";


const roboto_Mono = Roboto_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={roboto_Mono.className}>
        {/* <StoreProvider> */}
        <AuthenticateHandler>
          <Provider>
            <div className="flex">
              {/* <SideNav/> */}
              <SideNavWrapper />
              <main className="flex-1 p-10">{children}</main>
            </div>
          </Provider>
          <Toaster position="top-right" />
        </AuthenticateHandler>
        {/* </StoreProvider> */}
      </body>
    </html>
  );
}
